openapi: 3.0.0

info:
  title: Test API
  version: 0.1.0

paths:
  '/test':
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schema'
      responses:
        '200':
          content:
            application/json:
              schema:
                foo:
                  type: string
components:
  schemas:

    Schema:
      allOf:
        - oneOf:
          - $ref: '#/components/schemas/OneOfFirst'
          - $ref: '#/components/schemas/OneOfSecond'
        - type: object
          properties:
            foobar:
              type: string

    OneOfFirst:
      type: object
      properties:
        foo:
          type: string

    OneOfSecond:
      type: object
      properties:
        bar:
          type: string
